spring.application.name=old_bicycle_project

# Bỏ qua bắt buộc lấy từ ENV ở môi trường dev để test chạy được Swagger
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

# H2 Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# Cho phép Flyway vô hiệu hóa ở H2 để Spring Data JPA tự tạo table bằng Hibernate
spring.flyway.enabled=false

jwt.secret=bW90X2NodW9pX2JpX21hdF9yYXRfZGFpX3ZhX2FuX3RvYW5fZGVfa3lfdG9rZW5fZGFuZ19uaGFw
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

spring.mail.username=test@gmail.com
spring.mail.password=test

spring.security.oauth2.client.registration.google.client-id=test-client-id
spring.security.oauth2.client.registration.google.client-secret=test-client-secret

supabase.url=https://test.supabase.co
supabase.anon-key=test-anon-key
